### PR TITLE
Adds create, update, and delete methods

### PR DESCRIPTION
**Pull request by bostondv**
Hey there! I've added create, update, and delete methods for all the endpoints including posts, pages, comments, media, etc.

### CODE REVIEW

**Comment by shprink** [comment]
Awesome work man! Thanks very much :)

**Comment by bostondv** [comment]
No prob! Glad to see it merged :tada:

**Comment by shprink** [comment]
Have not tested yet though. Have you?

**Comment by bostondv** [comment]
Yeah I updated the tests and those are running successfully but I've also
used some of the methods in an app I'm building with WPHC with success.
Would be good if you can have a look through as well though just to be sure
I have't missed anything.

**Comment by shprink** [comment]
Are you using the basic auth method to log in?

**Comment by bostondv** [comment]
In the tests yeah, though in the WPHC app I'm using
https://wordpress.org/plugins/wp-jwt-auth/

**Comment by shprink** [comment]
Great stuff, any chance to see your work on WPHC contributed?

**Comment by bostondv** [comment]
Definitely, as soon as I get the things to a place where its ready to :)

**Comment by tinytoolbox** [comment]
Boston is the man!

**Comment by shprink** [comment]
You guys rock!

**Comment by micko75** [comment]
Hi @bostondv please any chance to get help on the authentication part. Cant get to figure out how to connect from WPHC using wp-angular-js.
Thank you in advance.

**Pull request merged**
